name = "HerbData"
uuid = "495a3ad3-8034-41b3-a087-aacf2fd71098"
authors = ["jaapjong <J.deJong-18@student.tudelft.nl>"]
version = "0.1.0"

[compat]
julia = "1.8"

[deps]
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
